name: Cron Test

on:
  schedule:
    - cron: '* * * * *'  # Runs every minute

jobs:
  test-cron:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create timestamp file
      run: |
        echo "Current timestamp: $(date)" >> cron-test.log
